# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0fc6ba34a6e6ea3e0df48a758dfa5437"
name = "flashOff"
handle = "flashoff"
application_url = "https://have-lan-blond-running.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "test-store-xo12.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [
  "https://have-lan-blond-running.trycloudflare.com/auth/callback",
  "https://have-lan-blond-running.trycloudflare.com/auth/shopify/callback",
  "https://have-lan-blond-running.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
